# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=2)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachinePath',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='machinechoice',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttt.MachinePath'),
        ),
    ]
