# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinechoice',
            name='value',
            field=models.FloatField(),
        ),
    ]
